// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATItCilBP1pRaOeGc6dubn-BPfYijOyyM',
    appId: '1:818230008289:web:cf9db62bd5b41a6cb8daa0',
    messagingSenderId: '818230008289',
    projectId: 'firepomodoro',
    authDomain: 'firepomodoro.firebaseapp.com',
    storageBucket: 'firepomodoro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOhcgCapv2YKsKhj0vmg6wScPspAGs3Ck',
    appId: '1:818230008289:android:8703617a3ca8531eb8daa0',
    messagingSenderId: '818230008289',
    projectId: 'firepomodoro',
    storageBucket: 'firepomodoro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpYdCt6Cy1ij9qmeUo2nb_a466fErsLY',
    appId: '1:818230008289:ios:bdd4cda57f068bf9b8daa0',
    messagingSenderId: '818230008289',
    projectId: 'firepomodoro',
    storageBucket: 'firepomodoro.appspot.com',
    iosBundleId: 'com.example.pomodoroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpYdCt6Cy1ij9qmeUo2nb_a466fErsLY',
    appId: '1:818230008289:ios:92d95849c4e9cf2fb8daa0',
    messagingSenderId: '818230008289',
    projectId: 'firepomodoro',
    storageBucket: 'firepomodoro.appspot.com',
    iosBundleId: 'com.example.pomodoroApp.RunnerTests',
  );
}
